#!/usr/bin/env node

/**
 * Arduino Test Bed
 * A utiliy that checks each digital and analog pin on common arduino
 * types to ensure you have not fried your board.
 *
 * @author Jarred Kenny (jarred@jarredkenny.com)
 *
 */

var colors = require('colors/safe');
var arduino = require('./lib/arduino');
var pins  = require('./lib/pins');
var argv = require('yargs').argv;

if(argv.board === undefined){
  console.log('You did not specify a board type. Will attempt to auto detect.');
}

else if(pins[argv.board] === undefined){
  console.error(argv.board + " is not a supported board type.");
  return;
}

arduino.init();


arduino.onReady(function(board){

  for(var i = 0; i < pins[argv.board].digital.length; i++){
    arduino.addDigitalTest(pins[argv.board].digital[i]);
  }

  for(var i = 0; i < pins[argv.board].analog.length; i++){
    arduino.addAnalogTest(pins[argv.board].analog[i]);
  }


  arduino.runTests();
  setInterval(function(){

    if(arduino.testsComplete()){

      if(arduino.validateDigital()){
        console.log("Digital Pin Tests... " + colors.green("PASSED"));
        arduino.showSuccess();
      }else{
        console.log("Digital Pin Tests... " + colors.red("FAILED"));
        console.log("The following pins have failed: " + arduino.getFailedDigitalPins());
        arduino.showFailure();
      }

      if(arduino.validateAnalog()){
        console.log("Analog Pin Tests.... " + colors.green("PASSED"));
        arduino.showSuccess();
      }else{
        console.log("Analog Pin Tests.... " + colors.red("FAILED"));
        console.log("The following pins have failed: " + arduino.getFailedAnalogPins());
        arduino.showFailure();
      }

      process.exit();
    }
    return;
  }, 100);

});
